"use client";

import { useState } from "react";
import type { ApiEndpoint, ApiSection } from "@/types/api-docs";

export default function ApiDocsPage() {
  const [activeEndpoint, setActiveEndpoint] = useState<string | null>(null);
  const [copySuccess, setCopySuccess] = useState(false);

  const toggleEndpoint = (id: string) => {
    setActiveEndpoint(activeEndpoint === id ? null : id);
  };

  const apiSections: ApiSection[] = [
    {
      name: "Admin",
      endpoints: [
        {
          id: "admin-auth-login",
          method: "POST",
          path: "/api/admin/auth/login",
          description: "Authenticates an admin user and returns a JWT token",
          requestBody: {
            type: "json",
            example: JSON.stringify(
              {
                email: "admin@example.com",
                password: "password123",
              },
              null,
              2,
            ),
          },
          responseBody: {
            type: "json",
            example: JSON.stringify(
              {
                token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...",
                email: "admin@example.com",
                id: "clj2hf3g30000vx085zfhs7do",
                role: "ADMIN",
              },
              null,
              2,
            ),
          },
          parameters: [],
          headers: [],
        },
        {
          id: "admin-auth-create",
          method: "POST",
          path: "/api/admin/auth/create",
          description: "Creates a new admin user account",
          requestBody: {
            type: "json",
            example: JSON.stringify(
              {
                email: "new.admin@example.com",
                password: "securePassword123",
                name: "Admin User",
              },
              null,
              2,
            ),
          },
          responseBody: {
            type: "json",
            example: JSON.stringify(
              {
                id: "clj2hf3g30000vx085zfhs7do",
                email: "new.admin@example.com",
                name: "Admin User",
                role: "ADMIN",
              },
              null,
              2,
            ),
          },
          parameters: [],
          headers: [],
        },
        {
          id: "admin-paper-assign-editor",
          method: "POST",
          path: "/api/admin/paper/assign",
          description: "Assigns an Editor to a paepr",
          requestBody: {
            type: "json",
            example: JSON.stringify(
              {
                paperId: "some-paper-di",
                employeeId: "unique ID generated by the system",
              },
              null,
              2,
            ),
          },
          responseBody: {
            type: "json",
            example: JSON.stringify(
              {
                newPapers: [
                  {
                    id: "author_67890",
                    submissionId: "JCT_25_001",
                    name: "Prof. Kenji Tanaka",
                    keywords: [
                      "AI Ethics",
                      "Machine Learning",
                      "Neural Networks",
                    ],
                    manuscriptId: "manuscript_13579",
                    manuscriptUrl:
                      "https://example.com/manuscripts/ai_ethics_tanaka.pdf",
                    publishId: "pub_1a2b3c",
                    publishUrl:
                      "https://journalofai.com/articles/vol23/issue4/tanaka",
                    archiveId: "archive_wxyz01",
                  },
                ],
              },
              null,
              2,
            ),
          },
          parameters: [
            {
              name: "paperId",
              description: "Unique ID of the paper",
              required: true,
              type: "body",
            },
            {
              name: "employeeId",
              description: "Unique ID of the employee",
              required: true,
              type: "body",
            },
          ],
          headers: [
            {
              name: "Authorization",
              description: "Bearer token for authentication",
              required: true,
            },
          ],
        },
        {
          id: "admin-paper-status-update",
          method: "POST",
          path: "/api/admin/paper/status",
          description:
            "Admin directly updates the new status no need of approval",
          requestBody: {
            type: "json",
            example: JSON.stringify(
              {
                status: "DRAFT",
                comments:
                  "Excellent work. The methodology is sound and the conclusions are well-supported by the data. Minor grammatical revisions suggested in the attached file.",
                paperId: "JCT_25_001",
                file: "https://example.com/path/to/reviewed_document.pdf",
              },
              null,
              2,
            ),
          },
          responseBody: {
            type: "json",
            example: JSON.stringify(
              {
                status: "REJECTED",
                id: "status_update_xyz789",
                createdAt: "2025-10-08T18:26:00Z",
                updatedAt: "2025-10-08T18:26:00Z",
                isApproved: false,
                paperId: "JCT-PAPER-2025-011",
                changedById: "editor_prof_jones_123",
                comments: [
                  "The conclusion is not well-supported by the provided data.",
                  "Significant revisions are required in the methodology section before this can be reconsidered.",
                  "Plagiarism check flagged sections 2 and 4 for review.",
                ],
              },
              null,
              2,
            ),
          },
          parameters: [
            {
              name: "status",
              description: "new status of the paper",
              required: true,
              type: "path",
            },
            {
              name: "comments",
              description: "a brief description about the modification",
              required: false,
              type: "body",
            },
            {
              name: "paperId",
              description: "An Unique ID of the paper",
              required: true,
              type: "body",
            },
            {
              name: "file",
              description:
                "A publishable file required only when publishing the articl3e",
              required: false,
              type: "body",
            },
          ],
          headers: [
            {
              name: "Authorization",
              description: "Bearer token for authentication",
              required: true,
            },
          ],
        },
        {
          id: "admin-paper-status-approve",
          method: "PATCH",
          path: "/api/admin/paper/status",
          description:
            "Updates the status or details of a paper if it is reviewed an order is created an email is send to the author",
          requestBody: {
            type: "json",
            example: JSON.stringify(
              {
                statusRecordId: "ID of the status to be approved",
              },
              null,
              2,
            ),
          },
          responseBody: {
            type: "json",
            example: JSON.stringify(
              {
                paper: {
                  authors: [
                    {
                      id: "author_aryank_123",
                    },
                    {
                      id: "author_coauthor_456",
                    },
                  ],
                },
                status: "UNDER_REVIEW",
                id: "status_update_pqr678",
                isApproved: false,
                paperId: "JCT-PAPER-2025-042",
                changedById: "editor_prof_eva_789",
                comments: [
                  "The paper has been successfully submitted and is now pending reviewer assignment.",
                ],
                createdAt: "2025-10-08T18:35:00Z",
                updatedAt: "2025-10-08T18:35:00Z",
              },
              null,
              2,
            ),
          },
          parameters: [
            {
              name: "statusRecordId",
              description: "ID of the status to be approved",
              required: true,
              type: "body",
            },
          ],
          headers: [
            {
              name: "Authorization",
              description: "Bearer token for authentication",
              required: true,
            },
          ],
        },
        {
          id: "admin-archive-create",
          method: "POST",
          path: "/api/admin/archive",
          description: "Creates new archives for the Papers",
          requestBody: {
            type: "json",
            example: JSON.stringify(
              {
                volume: "8",
                issue: "1",
                month: "January",
                year: "2025",
              },
              null,
              2,
            ),
          },
          responseBody: {
            type: "json",
            example: JSON.stringify(
              {
                id: "archive_vol12_iss4_oct2025",
                volume: 8,
                issue: 1,
                month: "January",
                year: 2025,
                createdAt: "2025-10-08T18:39:54Z",
                updatedAt: "2025-10-08T18:39:54Z",
              },
              null,
              2,
            ),
          },
          parameters: [
            {
              name: "volume",
              description: "The number of current volume",
              type: "body",
              required: true,
            },
            {
              name: "issue",
              description: "The number of current issue",
              type: "body",
              required: true,
            },
            {
              name: "Month",
              description: "The name of the current month",
              type: "body",
              required: true,
            },
            {
              name: "year",
              description: "The year of the archive",
              type: "body",
              required: true,
            },
          ],
          headers: [
            {
              name: "Authorization",
              description: "Bearer token for authentication",
              required: true,
            },
          ],
        },
        {
          id: "admin-archive-delete",
          method: "DELETE",
          path: "/api/admin/archive/[id]",
          description: "Removes the complete archive",
          requestBody: {
            type: "json",
            example: JSON.stringify(
              {
                id: "unique ID of the archive",
              },
              null,
              2,
            ),
          },
          responseBody: {
            type: "json",
            example: JSON.stringify(
              {
                id: "archive_vol12_iss4_oct2025",
                volume: 12,
                issue: 4,
                month: "October",
                year: 2025,
                createdAt: "2025-10-08T18:39:54Z",
                updatedAt: "2025-10-08T18:39:54Z",
              },
              null,
              2,
            ),
          },
          parameters: [
            {
              name: "id",
              description: "Archive ID",
              required: true,
              type: "body",
            },
          ],
          headers: [
            {
              name: "Authorization",
              description: "Bearer token for authentication",
              required: true,
            },
          ],
        },
        {
          id: "admin-archive-update",
          method: "PATCH",
          path: "/api/admin/archive/[id]",
          description:
            "Updates the existing archive at least one body parameter must be provided",
          requestBody: {
            type: "json",
            example: JSON.stringify(
              {
                volume: "8",
                issue: "1",
                month: "January",
                year: "2025",
              },
              null,
              2,
            ),
          },
          responseBody: {
            type: "json",
            example: JSON.stringify(
              {
                id: "archive_vol12_iss4_oct2025",
                volume: 12,
                issue: 4,
                month: "October",
                year: 2025,
                createdAt: "2025-10-08T18:39:54Z",
                updatedAt: "2025-10-08T18:39:54Z",
              },
              null,
              2,
            ),
          },
          parameters: [
            {
              name: "id",
              description: "Archive ID",
              required: true,
              type: "path",
            },
            {
              name: "volume",
              description: "The number of current volume",
              type: "body",
              required: true,
            },
            {
              name: "issue",
              description: "The number of current issue",
              type: "body",
              required: false,
            },
            {
              name: "Month",
              description: "The name of the current month",
              type: "body",
              required: false,
            },
            {
              name: "year",
              description: "The year of the archive",
              type: "body",
              required: false,
            },
          ],
          headers: [
            {
              name: "Authorization",
              description: "Bearer token for authentication",
              required: true,
            },
          ],
        },
      ],
    },
    {
      name: "Author",
      endpoints: [
        // {
        //     id: "author-auth-register",
        //     method: "POST",
        //     path: "/api/author/auth/register",
        //     description: "Registers a new author account",
        //     requestBody: {
        //         type: "json",
        //         example: JSON.stringify(
        //             {
        //                 name: "Author Name",
        //                 email: "author@example.com",
        //                 password: "securePassword123",
        //                 affiliation: "University"
        //             },
        //             null,
        //             2
        //         )
        //     },
        //     responseBody: {
        //         type: "json",
        //         example: JSON.stringify(
        //             {
        //                 id: "clj2hf3g30002vx085zfhs7d2",
        //                 name: "Author Name",
        //                 email: "author@example.com",
        //                 message: "Registration successful. Please verify your email."
        //             },
        //             null,
        //             2
        //         )
        //     },
        //     parameters: [],
        //     headers: []
        // },
        // {
        //     id: "author-auth-login",
        //     method: "POST",
        //     path: "/api/author/auth/login",
        //     description: "Authenticates an author and returns a JWT token",
        //     requestBody: {
        //         type: "json",
        //         example: JSON.stringify(
        //             {
        //                 email: "author@example.com",
        //                 password: "securePassword123"
        //             },
        //             null,
        //             2
        //         )
        //     },
        //     responseBody: {
        //         type: "json",
        //         example: JSON.stringify(
        //             {
        //                 token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...",
        //                 name: "Author Name",
        //                 email: "author@example.com",
        //                 id: "clj2hf3g30002vx085zfhs7d2"
        //             },
        //             null,
        //             2
        //         )
        //     },
        //     parameters: [],
        //     headers: []
        // },
        {
          id: "author-paper-submit",
          method: "POST",
          path: "/api/author",
          description: "Allows an author to submit a new paper",
          requestBody: {
            type: "json",
            example: JSON.stringify(
              {
                file: {
                  name: "A_Novel_Approach_to_Neural_Networks.pdf",
                  type: "application/pdf",
                  size: 2450000,
                },
                paperName:
                  "A Novel Approach to Asynchronous Neural Network Training",
                archiveId: "archive_vol12_iss4_oct2025",
                authors:
                  '[{"firstName":"Aryan","lastName":"Kumar","email":"aryan.k@university.edu","phone":"+91-9876543210","affiliation":"OIST Bhopal","isCorresponding":true},{"firstName":"Jane","lastName":"Doe","email":"jane.d@research.com","phone":"+1-123-456-7890","affiliation":"Tech Research Institute","isCorresponding":false}]',
                keywords:
                  '["Machine Learning", "Neural Networks", "AI", "Asynchronous Training"]',
              },
              null,
              2,
            ),
          },
          responseBody: {
            type: "json",
            example: JSON.stringify(
              {
                id: "paper_01hceg5k2cnmmabcpqjxz5wz9r",
                submissionId: "JCT-2025-10-08-001",
                name: "A Review of Decentralized Systems for Academic Publishing",
                keywords: [
                  "Blockchain",
                  "Academic Publishing",
                  "Decentralization",
                  "Web3",
                ],
                authors: [
                  {
                    id: "author_ak_123",
                    name: "Aryan Kumar",
                  },
                  {
                    id: "author_jd_456",
                    name: "Jane Doe",
                  },
                ],
                manuscriptId: "ms_a1b2c3d4e5f6g7h8",
                manuscriptUrl:
                  "https://storage.provider.com/jct-manuscripts/ms_a1b2c3d4e5f6g7h8.pdf",
                publishId: null,
                publishUrl: null,
              },
              null,
              2,
            ),
          },
          parameters: [
            {
              name: "file",
              description: "the manuscript file",
              type: "body",
              required: true,
            },
            {
              name: "paperName",
              description: "title of the paper",
              type: "body",
              required: true,
            },
            {
              name: "archiveId",
              description: "ID of the archive",
              type: "body",
              required: true,
            },
            {
              name: "authors",
              description: "Stringifies array of authors",
              type: "body",
              required: true,
            },
            {
              name: "keywords",
              description: "Stringifies array of keywords",
              type: "body",
              required: false,
            },
            {
              name: "paperName",
              description: "title of the paper",
              type: "body",
              required: true,
            },
          ],
          headers: [
            {
              name: "Authorization",
              description: "Bearer token for authentication",
              required: true,
            },
          ],
        },
        // {
        //     id: "author-paper-list",
        //     method: "GET",
        //     path: "/api/author/paper/list",
        //     description: "Retrieves all papers submitted by the authenticated author",
        //     requestBody: {
        //         type: "none"
        //     },
        //     responseBody: {
        //         type: "json",
        //         example: JSON.stringify(
        //             {
        //                 papers: [
        //                     {
        //                         id: "clj2hf3g30000vx085zfhs7do",
        //                         title: "Paper Title 1",
        //                         status: "UNDER_REVIEW",
        //                         submittedAt: "2025-09-15T00:00:00.000Z"
        //                     },
        //                     {
        //                         id: "clj2hf3g30008vx085zfhs7d8",
        //                         title: "Paper Title 2",
        //                         status: "ACCEPTED",
        //                         submittedAt: "2025-08-10T00:00:00.000Z"
        //                     }
        //                 ]
        //             },
        //             null,
        //             2
        //         )
        //     },
        //     parameters: [],
        //     headers: [
        //         {
        //             name: "Authorization",
        //             description: "Bearer token for authentication",
        //             required: true
        //         }
        //     ]
        // },
        {
          id: "author-paper-status",
          method: "GET",
          path: "/api/author/status",
          description: "Retrieves the current status of the paper",
          requestBody: {
            type: "none",
          },
          responseBody: {
            type: "json",
            example: JSON.stringify(
              {
                status: "REJECTED",
                id: "status_update_xyz789",
                createdAt: "2025-10-08T18:26:00Z",
                updatedAt: "2025-10-08T18:26:00Z",
                isApproved: false,
                paperId: "JCT-PAPER-2025-011",
                changedById: "editor_prof_jones_123",
                comments: [
                  "The conclusion is not well-supported by the provided data.",
                  "Significant revisions are required in the methodology section before this can be reconsidered.",
                  "Plagiarism check flagged sections 2 and 4 for review.",
                ],
              },
              null,
              2,
            ),
          },
          parameters: [
            {
              name: "paperId",
              description: "Paper ID",
              required: true,
              type: "query",
            },
          ],
          headers: [],
        },
      ],
    },
    {
      name: "Editor",
      endpoints: [
        // {
        //     id: "editor-auth-login",
        //     method: "POST",
        //     path: "/api/editor/auth/login",
        //     description: "Authenticates an editor and returns a JWT token",
        //     requestBody: {
        //         type: "json",
        //         example: JSON.stringify(
        //             {
        //                 email: "editor@example.com",
        //                 password: "securePassword123"
        //             },
        //             null,
        //             2
        //         )
        //     },
        //     responseBody: {
        //         type: "json",
        //         example: JSON.stringify(
        //             {
        //                 token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...",
        //                 name: "Editor Name",
        //                 email: "editor@example.com",
        //                 id: "clj2hf3g30004vx085zfhs7d4"
        //             },
        //             null,
        //             2
        //         )
        //     },
        //     parameters: [],
        //     headers: []
        // },
        {
          id: "editor-paper-list",
          method: "GET",
          path: "/api/editor/papers",
          description:
            "Retrieves a list of papers assigned to the editor for review",
          requestBody: {
            type: "none",
          },
          responseBody: {
            type: "json",
            example: JSON.stringify(
              {
                papers: [
                  {
                    id: "author_12345",
                    submissionId: "submission_abcde",
                    name: "Dr. Eleanor Vance",
                    keywords: ["Quantum Physics", "String Theory", "Cosmology"],
                    manuscriptId: "manuscript_67890",
                    manuscriptUrl:
                      "https://example.com/manuscripts/quantum_vance.pdf",
                    publishId: null,
                    publishUrl: null,
                    archiveId: "archive_qrstuv",
                  },
                  {
                    id: "author_67890",
                    submissionId: "submission_fghij",
                    name: "Prof. Kenji Tanaka",
                    keywords: [
                      "AI Ethics",
                      "Machine Learning",
                      "Neural Networks",
                    ],
                    manuscriptId: "manuscript_13579",
                    manuscriptUrl:
                      "https://example.com/manuscripts/ai_ethics_tanaka.pdf",
                    publishId: "pub_1a2b3c",
                    publishUrl:
                      "https://journalofai.com/articles/vol23/issue4/tanaka",
                    archiveId: "archive_wxyz01",
                  },
                ],
                total: 2,
                page: 1,
                limit: 10,
              },
              null,
              2,
            ),
          },
          parameters: [
            // {
            //     name: "page",
            //     description: "Page number for pagination",
            //     required: false,
            //     type: "query"
            // },
            // {
            //     name: "limit",
            //     description: "Number of results per page",
            //     required: false,
            //     type: "query"
            // },
            // {
            //     name: "status",
            //     description: "Filter papers by status (ASSIGNED_FOR_REVIEW, REVIEWED)",
            //     required: false,
            //     type: "query"
            // }
          ],
          headers: [
            {
              name: "Authorization",
              description: "Bearer token for authentication",
              required: true,
            },
          ],
        },
        {
          id: "editor-paper-detail",
          method: "GET",
          path: "/api/editor/paper/[id]",
          description: "Retrieves statuses",
          requestBody: {
            type: "none",
          },
          responseBody: {
            type: "json",
            example: JSON.stringify(
              [
                {
                  id: "status_update_abc123",
                  status: "SUBMITTED",
                  isApproved: false,
                  changedById: "author_aryank_123",
                  comments: ["Initial submission received."],
                  createdAt: "2025-10-08T19:10:00Z",
                  updatedAt: "2025-10-08T19:10:00Z",
                  paperId: "paper_01hceg5k2c123abc456def789",
                  paper: {
                    id: "paper_01hceg5k2c123abc456def789",
                    createdAt: "2025-10-08T19:10:00Z",
                    updatedAt: "2025-10-08T19:15:00Z",
                    name: "A Review of Decentralized Systems for Academic Publishing",
                    submissionId: "JCT-2025-10-08-001",
                    keywords: [
                      "Blockchain",
                      "Academic Publishing",
                      "Decentralization",
                    ],
                    manuscriptId: "ms_a1b2c3d4e5f6g7h8",
                    manuscriptUrl:
                      "https://storage.provider.com/jct-manuscripts/ms_a1b2c3d4e5f6g7h8.pdf",
                    publishId: null,
                    publishUrl: null,
                    archiveId: "archive_vol12_iss4_oct2025",
                  },
                },
                {
                  id: "status_update_def456",
                  status: "UNDER_REVIEW",
                  isApproved: false,
                  changedById: "editor_prof_eva_789",
                  comments: ["Paper has been assigned to reviewers."],
                  createdAt: "2025-10-08T19:15:00Z",
                  updatedAt: "2025-10-08T19:15:00Z",
                  paperId: "paper_01hceg5k2c123abc456def789",
                  paper: {
                    id: "paper_01hceg5k2c123abc456def789",
                    createdAt: "2025-10-08T19:10:00Z",
                    updatedAt: "2025-10-08T19:15:00Z",
                    name: "A Review of Decentralized Systems for Academic Publishing",
                    submissionId: "JCT-2025-10-08-001",
                    keywords: [
                      "Blockchain",
                      "Academic Publishing",
                      "Decentralization",
                    ],
                    manuscriptId: "ms_a1b2c3d4e5f6g7h8",
                    manuscriptUrl:
                      "https://storage.provider.com/jct-manuscripts/ms_a1b2c3d4e5f6g7h8.pdf",
                    publishId: null,
                    publishUrl: null,
                    archiveId: "archive_vol12_iss4_oct2025",
                  },
                },
              ],
              null,
              2,
            ),
          },
          parameters: [
            {
              name: "id",
              description: "Paper ID",
              required: true,
              type: "path",
            },
          ],
          headers: [
            {
              name: "Authorization",
              description: "Bearer token for authentication",
              required: true,
            },
          ],
        },
        {
          id: "editor-paper-update-status",
          method: "POST",
          path: "/api/editor/paper/[id]/status",
          description: "Allows an editor to update the status of the paper",
          requestBody: {
            type: "json",
            example: JSON.stringify(
              {
                status: "ACCEPT", // or "REJECT", "REVISE"
                comments: [
                  "The paper is well-structured and the methodology is sound.",
                ],
              },
              null,
              2,
            ),
          },
          responseBody: {
            type: "json",
            example: JSON.stringify(
              {
                success: true,
              },
              null,
              2,
            ),
          },
          parameters: [
            {
              name: "id",
              description: "Paper ID",
              type: "path",
              required: true,
            },
            {
              name: "status",
              description: "New status for the paper",
              type: "body",
              required: true,
            },
            {
              name: "comments",
              description: "stringifies array of comments",
              type: "body",
              required: false,
            },
          ],
          headers: [
            {
              name: "Authorization",
              description: "Bearer token for authentication",
              required: true,
            },
          ],
        },
        {
          id: "editor-paper-status-add-comment",
          method: "PATCH",
          path: "/api/editor/paper/[id]/status",
          description: "Add comments to the current status",
          requestBody: {
            type: "json",
            example: JSON.stringify(
              {
                statusId: "status_update_abc123",
                comments: ["Please address the following points..."],
              },
              null,
              2,
            ),
          },
          responseBody: {
            type: "json",
            example: JSON.stringify(
              {
                paperId: "JCT-PAPER-2025-055",
                status: "NEEDS_REVISION",
                comments: [
                  "The methodology is sound, but the conclusion needs to be strengthened with more data.",
                  "Please revise Figure 2 for clarity.",
                  "The literature review is missing some key recent publications in the field.",
                ],
                id: "status_update_ghi789",
                isApproved: false,
                createdAt: "2025-10-08T19:29:30Z",
                updatedAt: "2025-10-08T19:29:30Z",
                changedById: "reviewer_dr_adams_321",
              },
              null,
              2,
            ),
          },
          parameters: [
            {
              name: "id",
              description: "Paper ID",
              required: true,
              type: "path",
            },
            {
              name: "status",
              description: "new updated status for the paper",
              required: false,
              type: "body",
            },
            {
              name: "comments",
              description: "stringifies arrays of the comments",
              required: false,
              type: "path",
            },
          ],
          headers: [
            {
              name: "Authorization",
              description: "Bearer token for authentication",
              required: true,
            },
          ],
        },
      ],
    },
    {
      name: "Archive",
      endpoints: [
        {
          id: "list archives",
          method: "GET",
          path: "/api/archive",
          description: "Retrieves all archives and their papers",
          requestBody: {
            type: "none",
          },
          responseBody: {
            type: "json",
            example: JSON.stringify(
              {
                papers: [
                  [
                    {
                      id: "archive_vol12_iss4_oct2025",
                      volume: 12,
                      issue: 4,
                      month: "October",
                      year: 2025,
                      createdAt: "2025-10-01T10:00:00Z",
                      updatedAt: "2025-10-01T10:00:00Z",
                      papers: [
                        {
                          id: "paper_01hceg5k2c123abc456def789",
                          createdAt: "2025-08-15T09:30:00Z",
                          updatedAt: "2025-10-05T14:00:00Z",
                          name: "A Review of Decentralized Systems for Academic Publishing",
                          submissionId: "JCT-2025-08-015",
                          keywords: ["Blockchain", "Web3", "Publishing"],
                          manuscriptId: "ms_a1b2c3d4",
                          manuscriptUrl:
                            "https://storage.provider.com/jct/ms_a1b2c3d4.pdf",
                          publishId: "pub_a1b2c3d4",
                          publishUrl:
                            "https://jct.dev/archives/2025/vol12/iss4/paper1",
                          archiveId: "archive_vol12_iss4_oct2025",
                        },
                      ],
                      _count: {
                        papers: 1,
                      },
                    },
                    {
                      id: "archive_vol12_iss3_sep2025",
                      volume: 12,
                      issue: 3,
                      month: "September",
                      year: 2025,
                      createdAt: "2025-09-01T10:00:00Z",
                      updatedAt: "2025-09-01T10:00:00Z",
                      papers: [
                        {
                          id: "paper_2a7hfk9p8d123zyx456wqr234",
                          createdAt: "2025-07-20T11:00:00Z",
                          updatedAt: "2025-09-04T18:00:00Z",
                          name: "Advancements in Neural Network Optimization",
                          submissionId: "JCT-2025-07-020",
                          keywords: ["AI", "Machine Learning", "Optimization"],
                          manuscriptId: "ms_e5f6g7h8",
                          manuscriptUrl:
                            "https://storage.provider.com/jct/ms_e5f6g7h8.pdf",
                          publishId: "pub_e5f6g7h8",
                          publishUrl:
                            "https://jct.dev/archives/2025/vol12/iss3/paper1",
                          archiveId: "archive_vol12_iss3_sep2025",
                        },
                        {
                          id: "paper_3b8igj8q7c123xyz567vrs123",
                          createdAt: "2025-07-22T12:00:00Z",
                          updatedAt: "2025-09-06T19:00:00Z",
                          name: "The Impact of Quantum Computing on Cryptography",
                          submissionId: "JCT-2025-07-022",
                          keywords: [
                            "Quantum Computing",
                            "Cryptography",
                            "Security",
                          ],
                          manuscriptId: "ms_i9j0k1l2",
                          manuscriptUrl:
                            "https://storage.provider.com/jct/ms_i9j0k1l2.pdf",
                          publishId: "pub_i9j0k1l2",
                          publishUrl:
                            "https://jct.dev/archives/2025/vol12/iss3/paper2",
                          archiveId: "archive_vol12_iss3_sep2025",
                        },
                      ],
                      _count: {
                        papers: 2,
                      },
                    },
                    {
                      id: "archive_vol11_iss12_dec2024",
                      volume: 11,
                      issue: 12,
                      month: "December",
                      year: 2024,
                      createdAt: "2024-12-01T10:00:00Z",
                      updatedAt: "2024-12-01T10:00:00Z",
                      papers: [],
                      _count: {
                        papers: 0,
                      },
                    },
                  ],
                ],
              },
              null,
              2,
            ),
          },
          parameters: [
            {
              name: "page",
              description: "Page number for pagination",
              required: false,
              type: "query",
            },
            {
              name: "limit",
              description: "Number of results per page",
              required: false,
              type: "query",
            },
            {
              name: "keyword",
              description: "Filter papers by keyword",
              required: false,
              type: "query",
            },
            {
              name: "author",
              description: "Filter papers by author name",
              required: false,
              type: "query",
            },
          ],
          headers: [],
        },
      ],
    },
  ];

  const totalEndpoints = apiSections.reduce(
    (sum, section) => sum + section.endpoints.length,
    0,
  );

  const handleCopyCode = async (endpoint: ApiEndpoint) => {
    const functionName = "callApiEndpoint";
    const baseUrl = "http://localhost:3000";

    // Build headers string cleanly
    const headers = endpoint.headers
      .map(
        (h) =>
          `'${h.name}': '${
            h.name === "Authorization" ? "Bearer YOUR_TOKEN" : "YOUR_VALUE"
          }'`,
      )
      .join(",\n      ");

    // Add request body only if not GET
    const body =
      endpoint.method !== "GET" && endpoint.requestBody?.type === "json"
        ? `,\n    body: JSON.stringify(${JSON.stringify(
            endpoint.requestBody.example,
            null,
            2,
          )})`
        : "";

    // Build the example code dynamically
    const exampleCode = `
/**
 * Example using Fetch API
 */
async function ${functionName}() {
  const url = '${baseUrl}${endpoint.path}';
  const options = {
    method: '${endpoint.method}',
    headers: {
      'Content-Type': 'application/json',
      ${headers}
    }${body}
  };

  try {
    const response = await fetch(url, options);
    const data = await response.json();
    console.log('✅ Success:', data);
  } catch (error) {
    console.error('❌ Error:', error);
  }
}

${functionName}();
    `.trim();

    try {
      await navigator.clipboard.writeText(exampleCode);
      setCopySuccess(true);
      setTimeout(() => setCopySuccess(false), 2000);
    } catch (err) {
      console.error("Failed to copy code:", err);
    }
  };

  return (
    <div className="container mx-auto px-4 py-8">
      {/* Header section with a bottom border for separation */}
      <div className="border-b border-slate-200 pb-8 mb-8 dark:border-slate-700">
        <h1 className="text-4xl font-bold tracking-tight text-slate-900 dark:text-slate-100">
          API Documentation
        </h1>
        <h2 className="mt-2 text-lg text-slate-600 dark:text-slate-400">
          A comprehensive guide to all {totalEndpoints} available endpoints.
        </h2>
      </div>

      <div className="mb-6">
        <p className="text-gray-700 mb-4 dark:text-slate-300">
          This documentation provides details about the available API endpoints
          in the application. Each endpoint is grouped by its functional area
          and includes information about request/response formats.
        </p>
        <div className="rounded-md bg-yellow-50 p-4 border border-yellow-200 dark:bg-yellow-900/20 dark:border-yellow-800/40">
          <div className="flex">
            <div className="flex-shrink-0">
              <svg
                className="h-5 w-5 text-yellow-400"
                xmlns="http://www.w3.org/2000/svg"
                viewBox="0 0 20 20"
                fill="currentColor"
                aria-hidden="true"
              >
                <path
                  fillRule="evenodd"
                  d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z"
                  clipRule="evenodd"
                />
              </svg>
            </div>
            <div className="ml-3">
              <h3 className="text-sm font-medium text-yellow-800 dark:text-yellow-200">
                Note
              </h3>
              <div className="mt-2 text-sm text-yellow-700 dark:text-yellow-300">
                <p>
                  All authenticated endpoints require a valid JWT token in the
                  Authorization header. Obtain a token by using the login
                  endpoint.
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>

      {apiSections.map((section) => (
        <div key={section.name} className="mb-10">
          <h2 className="text-2xl font-semibold mb-4 pb-2 border-b text-slate-900 border-slate-200 dark:text-slate-100 dark:border-slate-700">
            {section.name} APIs ({section.endpoints.length})
          </h2>

          <div className="space-y-6">
            {section.endpoints.map((endpoint) => (
              <div
                key={endpoint.id}
                className="border border-slate-200 dark:border-slate-700 rounded-lg overflow-hidden"
              >
                <div
                  className="flex items-center justify-between p-4 cursor-pointer bg-gray-50 hover:bg-gray-100 dark:bg-slate-800 dark:hover:bg-slate-700"
                  onClick={() => toggleEndpoint(endpoint.id)}
                >
                  <div className="flex items-center">
                    <span
                      className={`inline-block px-2.5 py-1 rounded-full text-xs font-semibold mr-4 ${
                        endpoint.method === "GET"
                          ? "bg-blue-100 text-blue-800 dark:bg-blue-900/50 dark:text-blue-300"
                          : endpoint.method === "POST"
                            ? "bg-green-100 text-green-800 dark:bg-green-900/50 dark:text-green-300"
                            : endpoint.method === "PATCH"
                              ? "bg-yellow-100 text-yellow-800 dark:bg-yellow-900/50 dark:text-yellow-300"
                              : endpoint.method === "DELETE"
                                ? "bg-red-100 text-red-800 dark:bg-red-900/50 dark:text-red-300"
                                : "bg-gray-100 text-gray-800 dark:bg-slate-700 dark:text-slate-300"
                      }`}
                    >
                      {endpoint.method}
                    </span>
                    <span className="font-mono text-sm text-slate-800 dark:text-slate-200">
                      {endpoint.path}
                    </span>
                  </div>
                  <svg
                    className={`h-5 w-5 transition-transform text-slate-500 ${activeEndpoint === endpoint.id ? "transform rotate-180" : ""}`}
                    xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 20 20"
                    fill="currentColor"
                  >
                    <path
                      fillRule="evenodd"
                      d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 011.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z"
                      clipRule="evenodd"
                    />
                  </svg>
                </div>

                {activeEndpoint === endpoint.id && (
                  <div className="p-4 border-t bg-white border-slate-200 dark:bg-slate-900 dark:border-slate-800">
                    <p className="text-gray-700 mb-4 dark:text-slate-300">
                      {endpoint.description}
                    </p>

                    {endpoint.headers.length > 0 && (
                      <div className="mb-4">
                        <h3 className="font-semibold text-sm mb-2 text-slate-600 dark:text-slate-300">
                          Headers
                        </h3>
                        <div className="bg-gray-50 p-3 rounded dark:bg-slate-800">
                          {endpoint.headers.map((header, idx) => (
                            <div key={idx} className="mb-1 last:mb-0">
                              <span className="font-mono text-xs text-slate-800 dark:text-slate-200">
                                {header.name}
                              </span>
                              {header.required && (
                                <span className="text-red-500 text-xs ml-1">
                                  *
                                </span>
                              )}
                              <span className="text-gray-500 text-xs ml-2 dark:text-slate-400">
                                - {header.description}
                              </span>
                            </div>
                          ))}
                        </div>
                      </div>
                    )}

                    {endpoint.parameters.length > 0 && (
                      <div className="mb-4">
                        <h3 className="font-semibold text-sm mb-2 text-slate-600 dark:text-slate-300">
                          Parameters
                        </h3>
                        <div className="bg-gray-50 p-3 rounded dark:bg-slate-800">
                          {endpoint.parameters.map((param, idx) => (
                            <div key={idx} className="mb-1 last:mb-0">
                              <span className="font-mono text-xs text-slate-800 dark:text-slate-200">
                                {param.name}
                              </span>
                              {param.required && (
                                <span className="text-red-500 text-xs ml-1">
                                  *
                                </span>
                              )}
                              <span className="text-gray-500 text-xs ml-2 dark:text-slate-400">
                                - {param.description} ({param.type})
                              </span>
                            </div>
                          ))}
                        </div>
                      </div>
                    )}

                    <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                      <div>
                        <h3 className="font-semibold text-sm mb-2 text-slate-600 dark:text-slate-300">
                          Request Body
                        </h3>
                        {endpoint.requestBody.type === "json" ? (
                          <pre className="bg-gray-900 text-gray-100 p-3 rounded text-xs overflow-auto max-h-60 dark:border dark:border-slate-700">
                            {endpoint.requestBody.example}
                          </pre>
                        ) : (
                          <p className="text-gray-500 italic text-sm dark:text-slate-400">
                            No request body required
                          </p>
                        )}
                      </div>

                      <div>
                        <h3 className="font-semibold text-sm mb-2 text-slate-600 dark:text-slate-300">
                          Response
                        </h3>
                        <pre className="bg-gray-900 text-gray-100 p-3 rounded text-xs overflow-auto max-h-60 dark:border dark:border-slate-700">
                          {endpoint.responseBody.example}
                        </pre>
                      </div>
                    </div>

                    <div className="mt-4">
                      <button
                        className="text-sm text-blue-600 hover:text-blue-800 font-medium dark:text-blue-400 dark:hover:text-blue-300"
                        onClick={() => handleCopyCode(endpoint)}
                      >
                        Copy Example Code
                      </button>
                    </div>
                  </div>
                )}
              </div>
            ))}
          </div>
        </div>
      ))}
    </div>
  );
}
